name: fdg_app
description: Finding a new way towards food inspiration

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  fdg_ui:
    path: packages/fdg_ui
  fdg_common:
    path: packages/fdg_common
  fdg_camera:
    path: packages/fdg_camera
  fdg_web_admin:
    path: packages/fdg_web_admin
  cupertino_icons: ^1.0.3
  easy_localization: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  effective_dart: ^1.3.1

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
